spring:
  application:
    name: vending-machine
  datasource:
    url: jdbc:postgresql://localhost:5432/vending
    username: vending-user
    password: vending-user
    driver-class-name: org.postgresql.Driver
  jpa: #Not a good idea for production init tables but good for quick task
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signing:
    key: i-am-signing-key

springdoc:
  swagger-ui:
    path: /api-docs/ui/swagger-ui/index.html
  api-docs:
    path: /api-docs